[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49990
Protocol = 'http'
StartupMsg = 'device virtual started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"
  UpdateLastConnected = false
  
# Pre-define Devices
[[DeviceList]]
  Name = "GPIOMoisture"
  Profile = "GPIO.Moist.Profile"
  Description = "GPIO Moisture sensor on a RP3"
  Labels = [ "RP3", "GPIO", "moisture"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "/api/v1/device/gpio"
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange = false
    Resource = 'Moisture'
