[Service]
Host = "localhost"
Port = 49984
ConnectRetries = 3
Labels = []
OpenMsg = "device gpio moisture sensor started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "192.168.0.2"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "192.168.0.2"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "192.168.0.2"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "192.168.0.2"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-gpio.log"
Level = "DEBUG"
  
# Pre-define Schedule Configuration
[[Schedules]]
Name = "10sec-schedule"
Frequency = "PT10S"

[[ScheduleEvents]]
Name = "readMoisture"
Schedule = "10sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/GPIOMoist1/Moisture"

# Pre-define Devices
[[DeviceList]]
  Name = "GPIOMoist1"
  Profile = "GPIO.Moist.Profile"
  Description = "GPIO Moisture sensor on a RP3"
  Labels = [ "RP3", "GPIO", "test"]

